export default {
    bgImages: [
        'https://ph.otos.online/ORMMc7Cg',
        'https://ph.otos.online/hNSsXPmX',
        'https://ph.otos.online/eJs6kWfT',
        'https://ph.otos.online/lDpjb5Ng',
        'https://ph.otos.online/UCH4jkh9',
        'https://ph.otos.online/4UPbxHjf',
        'https://ph.otos.online/e9vSU1S8',
        'https://ph.otos.online/Unw19xMn',
        'https://ph.otos.online/aMHwjsP4',
        'https://ph.otos.online/BtbAgexL',
        'https://ph.otos.online/SJl5XraH',
        'https://ph.otos.online/jDaTaV7W',
        'https://ph.otos.online/0jPDTPdm',
        'https://ph.otos.online/zQTKUoF0',
        'https://ph.otos.online/VLdMlltb',
        'https://ph.otos.online/fxg1USa1',
        'https://ph.otos.online/BaaWx4ft',
        'https://ph.otos.online/j3RF3XFd',
        'https://ph.otos.online/YNxxJmAP',
        'https://ph.otos.online/MvSpm9w3',
        'https://ph.otos.online/AIRQ5tfN',
        'https://ph.otos.online/j7T5PuJM',
        'https://ph.otos.online/fYEXfGAu',
        'https://ph.otos.online/a5dOxFYk',
        'https://ph.otos.online/n60KgTMU',
        'https://ph.otos.online/ET1xf9IU',
        'https://ph.otos.online/JQAvQlCI',
        'https://ph.otos.online/bOrf7AnT',
        'https://ph.otos.online/C41RxbMu',
        'https://ph.otos.online/Is5vCER6',
        'https://ph.otos.online/3en10ROq',
        'https://ph.otos.online/I9Pz6c92'

    ],
    resourceServer: {
        api: 'https://sharemyphoto-apim.azure-api.net/api/Photo?bucketName=ph.otos.online&url=',
    }
}; 